### PR TITLE
Add branching instructions

### PR DESCRIPTION
**Pull request by cchan**

### CODE REVIEW

**Comment by lpan** [comment]
dank Mr. Goose!

great work on this one dude! I remember myself a few months ago only knowing four git commands :stuck_out_tongue: 

```
git add -A
git commit -m 'lmao'
git push
git pull
```

**Comment by cchan** [comment]
Same tho, you learn so much once you mess up your git history once

**Comment by cchan** [comment]
dank mr goose
I wonder if this works

**Comment by cchan** [comment]
dank mr goose
now does it work

[Approved with PullApprove](https://pullapprove.com/sexxis/website/pull-request/20/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=sexxis/website)

ayy

**Comment by cchan** [comment]
dank mr goose

[Approved with PullApprove](https://pullapprove.com/sexxis/website/pull-request/20/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=sexxis/website)

**Pull request merged**
